### PR TITLE
Use improved connection manager in playground

### LINKED ISSUE #445: Server config is broken when I make the name of the server have spaces
## Issue 

When I name the server and give it a space in the name, like "Asana MCP Server", it doesn't work in the LLM playground. The error I'm seeing is "Server configuration not found". I think what's happening is that there's a misalignment when we normalize the server name. Perhaps when we configure the server / connect to it, we don't normalize the server name properly. 

```
MastraError: Server configuration not found for name: ass_ana
    at Object.onRequest (file:///Users/matt8p/Desktop/inspector/node_modules/@mastra/mcp/dist/index.js:677:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  id: 'MCP_CLIENT_ON_REQUEST_ELICITATION_FAILED',
  domain: 'MCP',
  category: 'THIRD_PARTY',
  details: { serverName: 'ass_ana' },
  [cause]: Error: Server configuration not found for name: ass_ana
```

### PR DESCRIPTION
**Pull request by chelojimenez**
This PR does two main things:
 * We stop normalizing with custom regex and generate UUIDs instead. 
 * Make chat.ts use our new connection manager
 
 The issue below pointed out about collision errors which were fixed by ussing UUIDS and we extended this to the chat tab
 
 Tested similar named mcp servers work on playground + don't break elicitation
 
image

closes #445

### CODE REVIEW

File: server/routes/mcp/chat.ts [hunk 1]
```diff
@@ -75,6 +70,9 @@ try {
 // Store for pending elicitation requests
 const pendingElicitations = new Map<string, PendingElicitation>();
 
+// Shared MCPJamClientManager instance for chat
+const mcpClientManager = new MCPJamClientManager();
```
Comment (matteo8p) [inline server/routes/mcp/chat.ts:74]: Instead of creating a new `mcpClientManager` can we use the global one from `c.mcpClientManager`?

File: server/services/mcpjam-client-manager.ts [hunk 2]
```diff
@@ -288,27 +337,30 @@ class MCPJamClientManager {
...
   getPromptsForServer(serverId: string): DiscoveredPrompt[] {
-    const id = normalizeServerId(serverId);
+    const id = this.getServerUniqueId(serverId);
+    if (!id) return [];
     return Array.from(this.promptRegistry.values()).filter(
       (p) => p.serverId === id,
     );
   }
 
   async executeToolDirect(
```
Comment (matteo8p) [inline server/services/mcpjam-client-manager.ts:347]: This function got really complicated. I think it would make it more simple if we passed in serverId the same way we did for other functions. 

We probably have to consider re-writing / standardizing `mcpjamClientManager`, it's getting disorganized already LOL

**Comment by oso-jukumari** [comment]
> Should we be passing the uniqueId back to the client so the client knows the ids too, and can use them to call certain actions?

I agree, but we should address this in a follow up PR, this one's already clogged. But yeah, this would unlock us from saving multiple server configs with the same name too
